# Generated by Django 5.0.6 on 2024-08-07 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
