# Generated by Django 5.0.6 on 2024-08-08 01:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('idEquipmentLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workerPosition', models.CharField(max_length=100, null=True)),
                ('workerDni', models.CharField(max_length=8, null=True)),
                ('loanDate', models.DateField(default=django.utils.timezone.now)),
                ('loanAmount', models.IntegerField(default=0)),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now)),
                ('manager', models.CharField(default='', max_length=100)),
                ('workOrder', models.IntegerField(default=0)),
                ('loanStatus', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.equipment')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_loans', to='almacen.worker')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLoan',
            fields=[
                ('idMaterialLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workerPosition', models.CharField(max_length=100, null=True)),
                ('workerDni', models.CharField(max_length=8, null=True)),
                ('loanDate', models.DateField(default=django.utils.timezone.now)),
                ('loanAmount', models.IntegerField(default=0)),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now)),
                ('manager', models.CharField(default='', max_length=100)),
                ('workOrder', models.IntegerField(default=0)),
                ('loanStatus', models.BooleanField(default=False)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.material')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_loans', to='almacen.worker')),
            ],
        ),
    ]
