# Generated by Django 5.0.6 on 2024-08-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_tool_creationdate_alter_material_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(max_length=20),
        ),
    ]
