# Generated by Django 5.0.6 on 2024-08-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_equipment_creationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppe',
            name='comments',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
