# Generated by Django 5.0.6 on 2024-08-07 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_tool_creationdate_alter_material_creationdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('idEquipmentLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workerPosition', models.CharField(max_length=100, null=True)),
                ('workerDni', models.CharField(max_length=8, null=True)),
                ('loanDate', models.DateField(default=django.utils.timezone.now)),
                ('loanAmount', models.IntegerField(default=0)),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now)),
                ('manager', models.CharField(default='', max_length=100)),
                ('workOrder', models.IntegerField(default=0)),
                ('loanStatus', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.equipment')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_loans', to='almacen.worker')),
            ],
        ),
    ]
