# Generated by Django 5.0.6 on 2024-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_ppe_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppe',
            name='comments',
        ),
        migrations.AddField(
            model_name='ppeloan',
            name='comments',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
