# Generated by Django 5.0.6 on 2024-08-08 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_equipmentloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLoan',
            fields=[
                ('idMaterialLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workerPosition', models.CharField(max_length=100, null=True)),
                ('workerDni', models.CharField(max_length=8, null=True)),
                ('loanDate', models.DateField(default=django.utils.timezone.now)),
                ('loanAmount', models.IntegerField(default=0)),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now)),
                ('manager', models.CharField(default='', max_length=100)),
                ('workOrder', models.IntegerField(default=0)),
                ('loanStatus', models.BooleanField(default=False)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.material')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_loans', to='almacen.worker')),
            ],
        ),
    ]
